### ISSUE TITLE
Issues about fyrite pickaxe

### ISSUE THREAD

**Issue by ChromaPIE** [Sinhika/Netherrocks#10]
Right-clicking any blocks (maybe. because not tested) with a fyrite pickaxe will cause a immediate crash and the game will be brought back to the main menu after a VanillaFix crash report. The report is here and from it you can see other mods I've loaded and see if the crash was mainly caused by other mods but not by Netherrocks itself:
[crash-2019-10-03_16.00.14-client.txt](https://github.com/Sinhika/Netherrocks/files/3685247/crash-2019-10-03_16.00.14-client.txt)

And a small issue. Mining osmium ores from Mekanism with fyrite pickaxe will not trigger the ability of the pickaxe, so only the ore blocks are dropped, but not the ingot.

Hoping for your response.

_From a fan of Netherrocks mod._

**Comment by Sinhika** [comment]
I am no longer maintaining versions prior to 1.14.4. The problem should be fixed in 1.14 and later, though.
