### ISSUE TITLE
Furnaces not opening UIs after placement

### ISSUE THREAD

**Issue by vizthex123** [Sinhika/Netherrocks#16]
I've noticed all types of furnace will sometimes refuse to open their UI after being placed (and right-click on it).

But if I re-log or reload the game, it works fine.

Game log:
[latest.log](https://github.com/Sinhika/Netherrocks/files/6667662/latest.log)

**Comment by Sinhika** [comment]
Fixed as of version 1.16.5-2.3.6.5
