### ISSUE TITLE
Crash whilst playing minecraft

### ISSUE THREAD

**Issue by DatrixTHLK** [Sinhika/Netherrocks#3]
https://github.com/Sinhika/SimpleCore/issues/8
I just wanted to reference the issue above with you incase your mod was having issues. If you know of this already then you may close this and I'll wait for a fix.
NetherRocks: 1.4.5.2

**Comment by Sinhika** [comment]
See SimpleCore#8. Closed because that one is now closed.

**Comment by DatrixTHLK** [comment]
Sounds good. Thanks.
