### ISSUE TITLE
Nuggets

### ISSUE THREAD

**Issue by Lordician** [Sinhika/Netherrocks#8]
Pretty much the same suggestion as for simple ores, i would love to see nuggets of these metals.
This would make it just a bit more compatible with other mods.

**Comment by Sinhika** [comment]
This is a good idea. I could add it to the 1.11.2 version, or wait until the port to 1.12. Any preference?

**Comment by Lordician** [comment]
I posted it here and in simple ores, but i suppose the main discussion would take place in the simple ores one: https://github.com/Sinhika/SimpleOres2/issues/11

**Comment by Sinhika** [comment]
1.14.2 has nuggets.
